name: Build App with Unleashed Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Build FAP using the action with Unleashed firmware
      - name: Build FAP with Unleashed Firmware
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          sdk-index-url: https://up.unleashedflip.com/directory.json
          sdk-channel: dev
      
      # Upload the built FAP files as artifacts
      - name: Upload FAP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
          if-no-files-found: error